name: ecology-prac
channels:
  - r
  - conda-forge
  - bioconda
dependencies:
  - r-essentials
  - r-devtools
  - r-ggbiplot
  - nodejs=9
  - matplotlib
  - jupyterlab>=0.33
  - pip:
    - jupyterlab_latex
